
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioSumerImplService", targetNamespace = "http://beans/", wsdlLocation = "http://localhost:8080/ServicioSumerImplService/ServicioSumerImpl?wsdl")
public class ServicioSumerImplService
    extends Service
{

    private final static URL SERVICIOSUMERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOSUMERIMPLSERVICE_EXCEPTION;
    private final static QName SERVICIOSUMERIMPLSERVICE_QNAME = new QName("http://beans/", "ServicioSumerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ServicioSumerImplService/ServicioSumerImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOSUMERIMPLSERVICE_WSDL_LOCATION = url;
        SERVICIOSUMERIMPLSERVICE_EXCEPTION = e;
    }

    public ServicioSumerImplService() {
        super(__getWsdlLocation(), SERVICIOSUMERIMPLSERVICE_QNAME);
    }

    public ServicioSumerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOSUMERIMPLSERVICE_QNAME, features);
    }

    public ServicioSumerImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOSUMERIMPLSERVICE_QNAME);
    }

    public ServicioSumerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOSUMERIMPLSERVICE_QNAME, features);
    }

    public ServicioSumerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioSumerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioSumarWS
     */
    @WebEndpoint(name = "ServicioSumerImplPort")
    public ServicioSumarWS getServicioSumerImplPort() {
        return super.getPort(new QName("http://beans/", "ServicioSumerImplPort"), ServicioSumarWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioSumarWS
     */
    @WebEndpoint(name = "ServicioSumerImplPort")
    public ServicioSumarWS getServicioSumerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://beans/", "ServicioSumerImplPort"), ServicioSumarWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOSUMERIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICIOSUMERIMPLSERVICE_EXCEPTION;
        }
        return SERVICIOSUMERIMPLSERVICE_WSDL_LOCATION;
    }

}
